# Generated by Django 3.2.13 on 2023-06-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_orders_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='orders_quantity',
        ),
    ]
