# Generated by Django 3.2.13 on 2023-05-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quality',
            new_name='quantity',
        ),
    ]
